name: Deployment pipeline

env:
  IS_DEPLOY: ${{ (github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')) || (github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '#skip') && !contains(github.event.pull_request.body, '#skip')) }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Make a build
        run: npm run build

      - name: Run tests
        run: npm run test -- --coverage

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Bump version and push tag
        if: ${{ env.IS_DEPLOY == 'true' }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Railway CLI
        if: ${{ env.IS_DEPLOY == 'true' }}
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        if: ${{ env.IS_DEPLOY == 'true' }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --ci --service full-stack-open-pokedex

      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: |
            ðŸš€ Deployment for full-stack-open-pokedex completed!
            Commit: ${{ github.sha }}
            By: ${{ github.actor }}      
